### PR TITLE
pl - upgrade ruby to 2.3.3

### PR DESCRIPTION
**Pull request by pololee**

### CODE REVIEW

**Comment by bboe** [comment]
Why not 2.4?

**Comment by pololee** [comment]
We are using 2.3.3 in apm_bundle https://github.com/appfolio/apm_bundle/blob/master/.ruby-version, so I figured we want to have the same version.

**Comment by bboe** [comment]
It's definitely good to update so we're at least on the same version, but one of the goals of this project was to also be on the latest so updating to 2.4.1, would be appropriate as well.

**Comment by pololee** [comment]
OK. I'll update it to the latest version then.

**Comment by pololee** [comment]
I'll just merge this PR since the developer laptop image has `2.3.3`.
I know we could ask new hire to install a different version, but it just costs more time during the setup session.
Let's upgrade it to the newest version when laptop image is updated.

**Pull request merged**
